spring:
  datasource:
    username: artists
    password: artists
    url: jdbc:mysql://localhost:3306/artists
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always